In [2]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
  Using cached filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.5/114.5 MB 381.0 kB/s eta 0:05:00
   ---------------------------------------- 0.5/114.5 MB 381.0 kB/s eta 0:05:00
   ---------------------------

In [3]:
import torch

# Scalar
scalar = torch.tensor(5)
print("Scalar:", scalar)

# Vector
vector = torch.tensor([1, 2, 3])
print("Vector:", vector)

# Matrix
matrix = torch.tensor([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

# Addition
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("Addition:", a + b)

# Matrix Multiplication
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
print("Matrix Multiplication:\n", torch.matmul(A, B))

# Reshaping
x = torch.arange(6)
print("Original:", x)
print("Reshaped (2x3):\n", x.reshape(2, 3))

Scalar: tensor(5)
Vector: tensor([1, 2, 3])
Matrix:
 tensor([[1, 2],
        [3, 4]])
Addition: tensor([5, 7, 9])
Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])
Original: tensor([0, 1, 2, 3, 4, 5])
Reshaped (2x3):
 tensor([[0, 1, 2],
        [3, 4, 5]])
